### ISSUE TITLE
Cannot extract large files (>4 GB)

### ISSUE THREAD

**Issue by edtechd** [antelle/node-stream-zip#10]
Hello, there is an issue with extracting of large files from ZIP archives.  It occurs with any files because CRC validation function operates with 32-bit values, but it needs to be changed when extracting more than 4GB of file data.

Here is my test code

```
						var outputFile = fs.createWriteStream("extracted.bin");
						var zip = new StreamZip({  
							file: "test.zip",  
							storeEntries: true    
						});
						zip.on('ready', function() {
							zip.stream("large_file_10GB.iso", function(error, zstream) {
								zstream.pipe(outputFile);
									zstream.on('end', function() { 
											console.log('entry end');
											return;
										});
							});
						});
```

It fails after extracting of 4GB with exception "Invalid CRC". Moreover, there is uncatched exception when the issue occurs

```
events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at emit (events.js:74:15)
    at onerror (_stream_readable.js:536:12)
    at emit (events.js:95:17)
    at onwriteError (_stream_writable.js:238:10)
    at onwrite (_stream_writable.js:256:5)
    at WritableState.onwrite (_stream_writable.js:96:5)
    at afterTransform (_stream_transform.js:99:5)
    at TransformState.afterTransform (_stream_transform.js:74:12)
    at EntryVerifyStream._transform (C:\Soft\Study\node_modules\node-stream-zip\
node_stream_zip.js:907:9)

```

Would it be possible to fix that?

**Comment by antelle** [comment]
Do you know any crc implementation in javascript which supports large files?
For example, in [buffer-crc32](https://github.com/brianloveswords/buffer-crc32/blob/master/index.js) it's the same.
> uncatched exception when the issue occurs

It's client responsibility, to attach `error` event listener to the stream you are using.

**Comment by antelle** [comment]
I made some investigation: created a 5GB-archive with test.bin file consisting of ~5G zero bytes:
```sh
$ dd if=/dev/zero of=test.bin bs=1 count=0 seek=5024102410
$ 7za a large5gb.zip test.bin 
$ zipinfo large5gb.zip 
Archive:  large5gb.zip   5895577 bytes   1 file
-rw-r--r--  6.3 unx 4294967295 bx defN 22-Jul-16 23:36 test.bin
1 file, 4294967295 bytes uncompressed, 5895395 bytes compressed:  99.9%
$ crc32 test.bin 
f9a7b7bd
$ node test-node-stream-zip
Reading entry: CRC f9a7b7bd, size: 4294967295
CRC: d202ef8d, expected f9a7b7bd
Size: 4294967296, expected 4294967295
```
So, we read size incorrectly.

**Comment by antelle** [comment]
Fixed. Please update to v1.3.4 and test if it works for you.

**Comment by edtechd** [comment]
Yes, it seems that zip64 uses the same crc32 technique to check crc, so the issue is somewhere else. Did you try to extract the file with node-stream-zip? I suppose that I get "Invalid CRC" error because extracting stopped at 4 GB, so trimmed file is checked for crc.

And I get correct size values when reading zip entry

`{"verMade":798,"version":45,"flags":0,"method":0,"time":1216177811,"crc":149982512,"compressedSize":4652994560,"size":4652994560,"fnameLen":56,"extraLen":44,"comLen":0,"diskStart":0,"inattr":0,"attr":2175008768,"offset":19889,"headerOffset":7642907266,"name":"test.iso","isDirectory":false,"comment":null}`

**Comment by antelle** [comment]
Yes, the size was updated to incorrect value later, while reading local entry header. Now it should be ok.

**Comment by edtechd** [comment]
OK, thanks, I will check it and keep you updated in case of any issues.
