### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by prabhu** [antelle/node-stream-zip#108]
Looks like there isn't much activity in three years. Any replacements or alternatives for this project?

**Comment by antelle** [comment]
Well it still works. There are plenty of alternatives though

**Comment by DiscoNova** [comment]
Well ... the feature-set is comprehensive, there are only a few reported issues (many of which fall into "is this even an issue the package is supposed to handle" and/or pebkac-varieties) and the package is being used by super-many projects, so ... there isn't really too much that is actually in need of doing.

Dead projects are usually ones that only very few people use, and the "issues"-tab keeps filling with hundreds of monthly reports for issues that go forever unfixed. I believe the term OP is looking for is "mature".

But this is just my opinion.

**Comment by prabhu** [comment]
Thank you so much everyone. The question got answered. This issue can be closed.
