### ISSUE TITLE
Final callback or event when all entries have been processed

### ISSUE THREAD

**Issue by matylla** [antelle/node-stream-zip#11]
Does the library provide a final event when all entries have been streamed to disk?

I'd imagine something like this:

````js
var zip = new ZStream({
    file: "archive.zip",
    storeEntries: false
});

zip.on("entry", function (entry) {
    zip.stream(entry, function (err, readStream) {
        readStream.pipe(fs.createWriteStream("./output/" + entry.name));
    });
});

zip.on("complete", function () {
    // all entries have been processed/saved to disk
});
````

**Comment by antelle** [comment]
In your example, the library (node-stream-zip) returned you the stream and it's client, not library, who saves file to disk/network/whatever. The library doesn't know what's going on.
To extract with notification, you can use the following code, which triggers a callback:
```javascript
zip.extract(null, './temp/', function(err, count) {
    console.log('Extracted ' + count + ' entries');
});
```

**Comment by matylla** [comment]
The problem with `zip.extract()` is that it will extract all the files from the ZIP regardless of the file. What if one entry in a ZIP is a [Zip Bomb](https://en.wikipedia.org/wiki/Zip_bomb)? If would be nice to check each entry and than, once all the entries have been processed, emit a finish/complete event.

**Comment by antelle** [comment]
To extract file-by-file, pass file name to the first argument of `extract`:
```javascript
    zip.extract('node/benchmark/net/tcp-raw-c2s.js', './temp/', function(err) {
        console.log('Entry extracted');
    });
```

**Comment by antelle** [comment]
But again, what if someone adds a decompression bomb there?
If you don't trust the archive, you should add 'entry' event handler and check entries (size and entries count) inside it.
