### ISSUE TITLE
Errors thrown in data handler events are swallowed

### ISSUE THREAD

**Issue by aearly** [antelle/node-stream-zip#12]
Consider the code:

```js
zip = new StreamZip({file: 'foo.zip'});

zip.on('ready', () => {
  zip.on('entry', (entry) => {
    entry.stream((err, stream) => {
      stream.on('data', (data) => {
        if (isBad(data)) throw new Error('descriptive message!');
      })

      stream.pipe(transformStream);
    })
  });
});
```

I would expect the uncaught error here to be the "descriptive message" error.  Instead, what I get is:

```
     Uncaught Error: no writecb in Transform class
      at afterTransform (_stream_transform.js:71:33)
      at TransformState.afterTransform (_stream_transform.js:54:12)
      at EntryVerifyStream._transform (node_modules/node-stream-zip/node_stream_zip.js:913:9)
      at EntryVerifyStream.Transform._read (_stream_transform.js:167:10)
```

Investigating the source, it appears you are wrapping a callback in a `try`/`catch` block.  Since I am throwing an error later in the callback chain, that try/catch causes the callback to be called twice, leading to the "no writecb" error caused by a confused transform stream.

**Comment by antelle** [comment]
Hello,
there are two ways you can handle errors:
1.
```
zip.on('error', function(err) { ... });
```
2. subscribe to stream error after stream.pipe call

**Comment by aearly** [comment]
Adding an error handler to the zip stream or the destination stream doesn't change the behavior, nor would I expect it to.

I am not interested in handling the error, I just want to know what the exact error thrown in a data handler was.

**Comment by antelle** [comment]
Hm, what would you like to get? By the stack trace, it looks like, your transformStream stream is lacking `writecb` method. You mean, another error was really thrown?

**Comment by aearly** [comment]
I would like to get the original error -- the `"descriptive message!"` error I'm using for illustration purposes.

According, to the call stack, that error is being caught in the `EntryVerifyStream._transform` method, which causes a transform stream callback to be called twice.

Searching other issues led me to this: https://github.com/rvagg/through2/issues/1#issuecomment-21987655  ... calling a transform stream callback twice calls produces that exact error.

**Comment by antelle** [comment]
Thanks, I missed the error. Merged, added a test: https://github.com/antelle/node-stream-zip/blob/master/test/tests.js#L245

**Comment by aearly** [comment]
Thanks! :+1:   Things are working-- err, failing beautifully now. :smile:
