### ISSUE TITLE
Strange stream error

### ISSUE THREAD

**Issue by cyrilchapon** [antelle/node-stream-zip#15]
Hey.

Here's the stack :
- I've got a node.js script that unzips a file, and post content to an API (using node-stream-zip, and request.js)
- I've got a node.js server that handles the multipart query (using multer)

This doesn't work when streaming directly from a RAM entry stream :
```
Promise.promisify(zip.stream)(syntheseEntry.name)
.then(function(fileStream) {
  return requestPromise({
    url: 'http://localhost:1337/file',
    method: 'POST',
    formData: {
      file: {
        value: fileStream,
        options: {
          filename: syntheseEntry.name
        }
      }
    }
  });
})
```

The error raised on my server is *"Unexpected end of multipart data"* like [this one](https://stackoverflow.com/questions/43905675/error-unexpected-end-of-multipart-data-in-busboy-file-upload)

---------------

But this **does** work when going through a temp file :
```
Promise.promisify(zip.stream)(syntheseEntry.name)
.then(function(zipFileStream) {
  return new Promise(function(resolve, reject) {
    let tmpFilePath = path.join(
      os.tmpdir(),
      new ObjectID().toString()
    );
    let tmpFileWriteStream = fs.createWriteStream(tmpFilePath);
    zipFileStream.pipe(tmpFileWriteStream);
    zipFileStream.on('end', function(err) {
      if(err) return reject(err);
      return resolve(tmpFilePath);
    });
  });
})
.then(function(tmpFilePath) {
  return fs.createReadStream(tmpFilePath);
})
.then(function(fileStream) {
  return requestPromise({
    url: 'http://localhost:1337/file',
    method: 'POST',
    formData: {
      file: {
        value: fileStream,
        options: {
          filename: syntheseEntry.name
        }
      }
    }
  });
})
```

--------
The strange this is that [yauzl](https://github.com/thejoshwolfe/yauzl) library leads to exactly the same trouble, but I can make work request.js + multer stack with any other kind of stream.. oO

**Comment by antelle** [comment]
This error is not from node-stream-zip, I mean, it can be caused by it, but not produced inside our lib. Please try to narrow it down.

**Comment by cyrilchapon** [comment]
It's very hard to narrow it down. Actualy I was hoping that posting here would allow us to digg into it, and maybe find a node-stream-zip dependency (maybe common with yauzl), so I can post there and which can help everybody :]

**Comment by antelle** [comment]
well it shouldn't be hard if you save the content to a file, then run node-stream-zip as a separate test and see if the output it correct.

**Comment by cyrilchapon** [comment]
Saving content to a file is correct.

On the other hand, any other type of stream piped to a request.js request is also correct.

This is when piping a zip-stream to a request.js stream that fails.
