### ISSUE TITLE
Why did you create this? (I'm trying to find the "best" unzip module)

### ISSUE THREAD

**Issue by coolaj86** [antelle/node-stream-zip#19]
> ZIP parsing code has been partially forked from cthackers/adm-zip (MIT license).

I've been going through a bunch of different unzip libraries trying to find the "best" one and I see tons and tons of forks. Seems like there must be 1,000 zip libraries that just don't work well enough (jszip, yauzl, zip, adm-zip, unzipper, ...) because people just keep creating more.

I'm curious as to why `adm-zip` didn't work for you and what you see as the major advantages to this library so that I can make the best possible choice.

Obviously I have to run various tests to make sure the library I pick works for my use case, but I'd like to know your thoughts on why the others didn't suit your needs.

(as far as I can tell, this is the best - complete, working, minimal - of all the forks and variations)

**Comment by antelle** [comment]
If an archive fits into memory, adm-zip will be fine. I haven't found any js lib which could open archives more than 1G, so created this one.
