### ISSUE TITLE
Base64 Buffer

### ISSUE THREAD

**Issue by graywolf336** [antelle/node-stream-zip#2]
Is there anyway to take a Base64 Buffer and use it with this library? Basically I'm uploading a file and want to be able to process it, present some information to the user, and then process even more based upon the user's selection.

**Comment by antelle** [comment]
So, at the time of processing, the entire file is loaded into memory as base64? Then you should use the original library https://github.com/cthackers/adm-zip which can decompress it.
The point of this fork is to process large files (e.g. 1gb) without loading them at once.

**Comment by graywolf336** [comment]
Yes, it's an uploaded file which we have the Base64 string of. Thanks for the information, I will try out adm-zip.
