### ISSUE TITLE
entryDataSync throws string instead of error

### ISSUE THREAD

**Issue by coolaj86** [antelle/node-stream-zip#20]
Test
-----

```js
var data = zip.entryDataSync('DOES_NOT_EXIST');
```

Result
------

```
zip-test/node_modules/node-stream-zip/node_stream_zip.js:395
            throw err;
            ^
Entry not found
```

Why this is important
----------------------

It's not possible to see the stack trace to determine where the error is occurring when a string is thrown instead of an error.

**Comment by antelle** [comment]
Not only this function, actually. Should fixed in other places as well, feel free to contribute.
