### ISSUE TITLE
How to serialize reading of entries? Purpose of zip.close()?

### ISSUE THREAD

**Issue by coolaj86** [antelle/node-stream-zip#21]
I was suspecting that `zip.close()` would be the cue to read the next file (so that it's not reading multiple files at once), but it seems that `entry` continues to fire - even when `stream` or `extract` is in progress - without waiting for `zip.close()`.

**Comment by antelle** [comment]
Once you're done with the archive, you should call close() to clean resources, that's only about it. It will not stop current operations.

**Comment by coolaj86** [comment]
So `zip.close()` should NOT be closed after each `zip.extract()`, only ONCE when everything is complete?

**Comment by antelle** [comment]
Yes, exactly. Once you don't need the zip file, call close(), otherwise there will be errors (what I can see in #24)
