### ISSUE TITLE
Does this read entries by whole file, look-ahead, or the index at end of file?

### ISSUE THREAD

**Issue by coolaj86** [antelle/node-stream-zip#22]
Does this read through all of the bytes of the entire zip to obtain the entry index?

Or does it just read the index at the end of the file?

Or does it read into the file, find an entry, and skip a byte count to the next entry?

I'm just curious as a matter of comparing this to `ZJONSSON/node-unzipper`.

**Comment by antelle** [comment]
It reads index at the end if the file, then it reads entry headers inside the file.
When you request entries, it reads the actual content.

**Comment by coolaj86** [comment]
Can it handle the case of a file being streamed and the table of contents not being ready yet? Or can it only read from the TOC?

There are cases that I'd want to pass in a stream instead of a file name. For example, if I'm uploading a 1gb file by chunk and want it to be unpacked at about the same time that it's done uploading.

**Comment by antelle** [comment]
It doesn't seem to be possible. Technically, zip archives contain local headers inside them, but they must be read from the end. So, you will need the whole file before unpacking it.

**Comment by coolaj86** [comment]
I know some other libraries ignore the TOC and only read the local headers. Not saying I'd work on it any time soon, but would you be open to that type of strategy?

**Comment by antelle** [comment]
If it doesn't increase file size a lot - why not? It could be useful to have such flag. 👍
