### ISSUE TITLE
[SECURITY] Is entry.name sanitized or raw?

### ISSUE THREAD

**Issue by coolaj86** [antelle/node-stream-zip#23]
Maliciously crafted zip files could contain illegal paths such as `../../../../etc/passwd` or `/etc/passwd` or `d://system32/win32.dll` even though the relative path format such as `etc/passwd` is the legal, proper way to store a path.

Is `entry.name` sanitized?

**Comment by antelle** [comment]
It's raw.

**Comment by coolaj86** [comment]
What do you think about either of these?

A) Replacing the raw name with a sanitized version and providing an `entry.unsafeName` or `entry.rawName` for those that might have use for illegally named paths

B) Throwing an error when encountering an entry with an illegal and potentially dangerous name

**Comment by antelle** [comment]
Well, we cannot safely sanitize a file name, it's not that easy as replacing `..`. If archives are not trusted (e.g. they're uploaded), it's better to use some library to detect malicious file names and use `stream` instead of `extract` (i.e. write files outside node-stream-zip).
I'll mention it in the readme.

**Comment by coolaj86** [comment]
The known blacklist of illegal characters is actually pretty small.

If you wanted to support all sorts of esoteric file systems, you would have to know all of their rules, but as for zip I believe it's as simple as 

* must use unix slashes '/', not windows slashes '\'
* must not contain parent path characters '..'
* must not start with '/' or a drive letter such as 'c:'

I believe that this is correct:

https://github.com/thejoshwolfe/yauzl/blob/master/index.js#L594

**Comment by antelle** [comment]
Yes, let's add a simple check like this one, and an optional parameter to disable security checks.
Theoretically, depending on the environment, there could be [more](https://www.owasp.org/index.php/Unrestricted_File_Upload) malicious things in file names, but yes, simple checks like mentioned above should not harm anyway.

**Comment by antelle** [comment]
Added it, the flag to disable errors is `skipEntryNameValidation`.
