### ISSUE TITLE
Read compressed file referse

### ISSUE THREAD

**Issue by conradob** [antelle/node-stream-zip#27]
Hi, is there a way to read the compressed file from the end to start without load it in memory? Thanks.

**Comment by antelle** [comment]
Hi, I didn't get your question, sorry. What do you mean?

**Comment by conradob** [comment]
Sorry for that, I'm trying to list the entries in a reverse way starting from the end of the file.

**Comment by antelle** [comment]
Have you read readme?

**Comment by conradob** [comment]
Yes, I read. Couldn't find something related. Am I missing something?

**Comment by antelle** [comment]
Well, there are some examples here: https://github.com/antelle/node-stream-zip#usage
They are not working for you this way?
