### ISSUE TITLE
Error is thrown when the zip has a lot of folder hierarchies in them

### ISSUE THREAD

**Issue by SiddAjmera** [antelle/node-stream-zip#29]
So here's what I did. I tried extracting a folder with just one folder inside it. Now the parent folder and the folder inside it, both has images. So there wasn't any issue extracting it.

But when I try to extract a zip archive such as this: https://drive.google.com/file/d/1LdI3iy0Vp1fPPGdEgxW28za8-WV7J6Mo/view?usp=sharing

I get an error saying `Error: ENOENT: no such file or directory, mkdir`.

Now when I again go to the folder that I zipped and tried, and zip a sub folder, like just the `src/app` folder instead of the whole project folder that looks something like this:

![image](https://user-images.githubusercontent.com/5053266/32990056-0691f500-cd48-11e7-868a-9c66478b68bc.png)

I get the error. Also it's only creates empty folders at that time and doesn't create sub-folders starting from a point.

**Comment by antelle** [comment]
Fixed it. Example code:
```
const fs = require('fs');
const StreamZip = require('node-stream-zip');

const zip = new StreamZip({
    file: 'RecipeApp.zip',
    storeEntries: true
});
zip.on('ready', () => {
    fs.mkdirSync('extracted');
    zip.extract(null, './extracted', (err, count) => {
        console.log(err ? 'Extract error\n' + err : `Extracted ${count} entries`);
        zip.close();
    });
});
```

**Comment by SiddAjmera** [comment]
Can you please check if it's creating all the folders along with all the files properly? Because I did exactly the same thing and it's throwing me an error.

**Comment by antelle** [comment]
Is it with the same archive you posted above? It works ok for me.
