### ISSUE TITLE
Looking for typings

### ISSUE THREAD

**Issue by mmajcica** [antelle/node-stream-zip#36]
Does anyone have typings for this library? I would like to use it in TypeScript based project and if someone wrote the typing already, it will save me plenty of time.

Thanks

**Comment by antelle** [comment]
Probably no, but let's keep the open for some time.

**Comment by rbattala-ck** [comment]
Curious to know if this stand has changed.

**Comment by thomassuckow** [comment]
I'll just leave this here
```
declare module 'node-stream-zip' {
    import {Stream} from 'stream';

    interface StreamZipOptions {
        /**
         * File to read
         */
        file: string,
        /**
         * You will be able to work with entries inside zip archive, otherwise the only way to access them is entry event
         * 
         * default: true
         */
        storeEntries?: boolean,
        /**
         * By default, entry name is checked for malicious characters, like ../ or c:\123, pass this flag to disable validation errors
         * 
         * default: false
         */
        skipEntryNameValidation?: boolean,
        /**
         * Undocumented adjustment of chunk size
         * 
         * default: automatic
         */
        chunkSize?: number
    }

    class ZipEntry {
        name: string
        isDirectory: boolean
        isFile: boolean
        comment: string
        size: number
    }

    class StreamZip {
        constructor(config: StreamZipOptions);

        on(event: 'error', handler: (error: any) => void): void
        on(event: 'entry', handler: (entry: ZipEntry) => void): void
        on(event: 'ready', handler: () => void): void

        entry(entry:string) :ZipEntry
        entries() : ZipEntry[]

        entriesCount: number
    
        stream(entry:string, callback: (err: any | null, stream?: Stream) =>void):void
        entryDataSync(entry:string):Buffer
        openEntry(entry: string, callback: (err: any | null, entry?: ZipEntry) => void, sync: boolean):void
        extract(entry: string, outPath: string, callback: (err?: any) => void): void
        close(callback?: (err?: any) => void): void
    }
    export = StreamZip;
}
```

**Comment by sangimed** [comment]
> 
> 
> I'll just leave this here
> 
> ```
> declare module 'node-stream-zip' {
>     import {Stream} from 'stream';
> 
>     interface StreamZipOptions {
>         /**
>          * File to read
>          */
>         file: string,
>         /**
>          * You will be able to work with entries inside zip archive, otherwise the only way to access them is entry event
>          * 
>          * default: true
>          */
>         storeEntries?: boolean,
>         /**
>          * By default, entry name is checked for malicious characters, like ../ or c:\123, pass this flag to disable validation errors
>          * 
>          * default: false
>          */
>         skipEntryNameValidation?: boolean,
>         /**
>          * Undocumented adjustment of chunk size
>          * 
>          * default: automatic
>          */
>         chunkSize?: number
>     }
> 
>     class ZipEntry {
>         name: string
>         isDirectory: boolean
>         isFile: boolean
>         comment: string
>         size: number
>     }
> 
>     class StreamZip {
>         constructor(config: StreamZipOptions);
> 
>         on(event: 'error', handler: (error: any) => void): void
>         on(event: 'entry', handler: (entry: ZipEntry) => void): void
>         on(event: 'ready', handler: () => void): void
> 
>         entry(entry:string) :ZipEntry
>         entries() : ZipEntry[]
> 
>         entriesCount: number
>     
>         stream(entry:string, callback: (err: any | null, stream?: Stream) =>void):void
>         entryDataSync(entry:string):Buffer
>         openEntry(entry: string, callback: (err: any | null, entry?: ZipEntry) => void, sync: boolean):void
>         extract(entry: string, outPath: string, callback: (err?: any) => void): void
>         close(callback?: (err?: any) => void): void
>     }
>     export = StreamZip;
> }
> ```

How can I use this please ? I created a `node-stream-zip.d.ts` file in my project but when I try to import it, I get this error :  
![image](https://user-images.githubusercontent.com/857405/80636221-60de6280-8a5d-11ea-959e-5c8bcaab6cd8.png)

when I try to set the `esModuleInterop` flag, it breaks existing code.

**Comment by thomassuckow** [comment]
In your `tsconfig.json` make sure you specify `esModuleInterop` and configure your type roots for third party libraries.
![image](https://user-images.githubusercontent.com/3100037/80641809-4931ba80-8a1a-11ea-8229-3da8eff32ea2.png)

You won't need to use the * as syntax after enabling esModuleInterop
![image](https://user-images.githubusercontent.com/3100037/80641709-1daed000-8a1a-11ea-94f1-5b88e1716562.png)

How I laid out my types folder:
![image](https://user-images.githubusercontent.com/3100037/80641773-34552700-8a1a-11ea-9db0-39f91522a02c.png)

**Comment by sangimed** [comment]
> 
> 
> In your `tsconfig.json` make sure you specify `esModuleInterop` and configure your type roots for third party libraries.
> ![image](https://user-images.githubusercontent.com/3100037/80641809-4931ba80-8a1a-11ea-8229-3da8eff32ea2.png)
> 
> You won't need to use the * as syntax after enabling esModuleInterop
> ![image](https://user-images.githubusercontent.com/3100037/80641709-1daed000-8a1a-11ea-94f1-5b88e1716562.png)
> 
> How I laid out my types folder:
> ![image](https://user-images.githubusercontent.com/3100037/80641773-34552700-8a1a-11ea-9db0-39f91522a02c.png)
It works ! Thank you so much :)

**Comment by antelle** [comment]
Added types here: https://github.com/antelle/node-stream-zip/blob/master/node_stream_zip.d.ts
