### ISSUE TITLE
Migrate away from deprecated Buffer constructor calls

### ISSUE THREAD

**Issue by johnspurlock** [antelle/node-stream-zip#37]
Thanks for the great lib.

Later versions of Node output deprecation warnings about the `new Buffer()` calls.  They have [guidance](https://nodejs.org/en/docs/guides/buffer-constructor-deprecation/) on how to migrate them, maintaining backward compat if necessary.

**Comment by antelle** [comment]
Thanks, fixed it

**Comment by johnspurlock** [comment]
Verified fixed in 1.8.0, thanks!
