### ISSUE TITLE
Byte-array support

### ISSUE THREAD

**Issue by johnspurlock** [antelle/node-stream-zip#38]
I see the rationale for not supporting streams in #8 - makes sense.

However, for cases where zip file bytes are already read completely into memory, it would be nice to support this case directly, instead of having to write out a tmp file first.

Perhaps a direct Buffer/Uint8Array parameter to the constructor config - or the ability to pass a file system implementation into the config (which would also facilitate unit testing).

Thanks!

**Comment by antelle** [comment]
Hi! I would suggest using https://github.com/cthackers/adm-zip, this library is a fork of adm-zip. That's exactly the point of making this fork, to be able to read files without reading all of them into memory. I don't see any value supporting both modes, while there's another tool doing this job.

**Comment by johnspurlock** [comment]
I see, I was just talking about the read scenario, since I don't need all of the write stuff from adm-zip.

I just saw StreamZip.setFs, which might work as a fallback for my case.  Really like how small and focused this library is.

**Comment by antelle** [comment]
In theory, you can implement fs module, but probably it will be somewhat complicated, because we use different methods from there.

**Comment by johnspurlock** [comment]
Looks like given the way I'm using it, it will probably be open, fstat, close and read.  It would be nice to allow passing an optional custom fs into the instance via the config, instead of having to set it and potentially reset it globally.
