### ISSUE TITLE
Feature request: read ZIP file from File api

### ISSUE THREAD

**Issue by Keeo** [antelle/node-stream-zip#39]
Hi, 

in what state is support for browser? It would be great to add support for file-api or just extend the constructor to support something more generic than filename. 

https://developer.mozilla.org/en-US/docs/Web/API/File
It does support `Blob.slice([start[, end[, contentType]]])` so it should be able to mimic whatever this library needs.

**Comment by antelle** [comment]
Hi! Files loaded in browser can be read in full. In this case it will be easier to read them using any other js library, for example jszip, zipjs, and so on. This is somewhat out of scope of node-stream-zip.
