### ISSUE TITLE
Cannot read more than 65535 entries

### ISSUE THREAD

**Issue by Quergo** [antelle/node-stream-zip#4]
I have a zip archiv which contains 66430 jpeg files. When I open the archiv and fetch the entriesCount value it tells me that there are only 65535 entries available.

**Comment by antelle** [comment]
This is ZIP64 format, support should be implemented, I agree.

**Comment by antelle** [comment]
Implemented ZIP64 support in 1.3.0.
For me, it works, please test.
Still thinking how to create unit tests for it without committing 2MB file to repo...

**Comment by Quergo** [comment]
Very nice, it works for me too.

Tested it with some archives up to 170.000 Entries.
