### ISSUE TITLE
[Question] Can it work for video streamming?

### ISSUE THREAD

**Issue by DaniellMesquita** [antelle/node-stream-zip#40]
@antelle
I'm creating a video format that uses frames (PNG images) inside a .zip file.
Could the frames be extracted in live stream?
I mean, stream the frame files without need to download the full .zip?

**Comment by DaniellMesquita** [comment]
@antelle

**Comment by antelle** [comment]
Hi!
No, zip archives can’t be streamed. The header located in the end, and you need to download the whole file first.

**Comment by DaniellMesquita** [comment]
@antelle , thanks for your information.
Not wanting to bother you, but is there a compressed format that supports streamming?

**Comment by antelle** [comment]
Almost all video formats are already compressed, wrapping them probably doesn’t make a lot of sense.

**Comment by DaniellMesquita** [comment]
Yes, it makes sense:
https://usvformat.github.io/

**Comment by DaniellMesquita** [comment]
There is a streammable archive: https://stackoverflow.com/questions/48475351/untar-pack-a-tar-file-while-downloading-is-it-streamable
