### ISSUE TITLE
Unzip for some files fails with "Bad Archive" intermittently.

### ISSUE THREAD

**Issue by ShwetaTurakhia** [antelle/node-stream-zip#41]
Below is my code to unzip the files. I am getting the bad archives for good files. if I retry the unzip is successful. Can someone please help find the issue?

 ```public async unzipPayload(zipFilePath: string, tempFolder: string): Promise<string[]> {
        const files = new Array<any>();
        return new Promise((resolve, reject) => {
            const zip = new streamZip({
                file: zipFilePath
            });
            zip.on("error", (err) => {
                this.logger.error("Unable to unzip the file " + zipFilePath, err);
                return reject(err);
            });
            zip.on("ready", () => {
                const startTime = process.uptime();
                zip.extract(null, tempFolder, (err, count) => {
                    if (err) {
                        this.logger.error("Unable to extract the file " + zipFilePath, err);
                        return reject(err);
                    }
                    this.logger.info(`Extracted ${count} entries`);
                    zip.close();
                    const timeTaken = process.uptime() - startTime;
                    this.logger.info(`Time taken to unzip the file ${timeTaken} Entries read: ${zip.entriesCount}`);
                    return resolve(files);
                });
            });

            zip.on("extract", (entry, file) => {
                this.logger.info(`Extracted File ${file}`, entry);
                files.push(file);
            });
        });
    }

**Comment by antelle** [comment]
Please reopen with more details: 
- full stack traces
- error details
- example of “good files”

**Comment by ShwetaTurakhia** [comment]
Hi @antelle, The problem is there was no stack trace. The only log that the details printed was "Bad  Archive". I wanted to understand if there is anything wrong with the way I am doing extract and close.

**Comment by antelle** [comment]
The way it’s codes looks right, I don’t see anything wrong here.  
Is it possible to configure your logger so that it prints more info?

**Comment by ShwetaTurakhia** [comment]
Sure I can do that but 
```               this.logger.error("Unable to unzip the file " + zipFilePath, err);
this line should have printed the stack trace ideally. Is there a way I can fetch the stack trace out of error? I am printing the error as is and it only prints "Bad archive"

{
    "message": "Failed while handling the UI payload fileName - UI-v1.0-f1-1560423600-1560427200-1560462931.zip",
    "classname": "QueryLogDataLoaderService",
    "co-relationId": "7c8e8880-8e04-11e9-8553-fdb56e8744d0",
    "component-name": "COMPONENT_NAME_UNKNOWN",
    "version": "VERSION_UNKNOWN",
    "detail": "Bad archive",
    "level": "error"
}

**Comment by antelle** [comment]
Actually stack trace would not be very helpful in case of this error, most likely something is going wrong and additional debugging is required.

Do you have an example that would trigger this error?

**Comment by ShwetaTurakhia** [comment]
it is happening when there is a heavy load. As we if 50 files are uploaded to S3, then some lambda executions are throwing this error. If I rerun the lambda for the same file, it works. I feel it has something to do with the scale. I am planning to add retry logic as a mitigation in production. Any thoughts?

**Comment by antelle** [comment]
If you could reproduce it, it would help a lot. For example, make a simple script that tries to open 50 files in the same time. I quickly tried it and it didn’t give an error.
Alternatively, you can set up some additional debugging there, but it can be complicated.

**Comment by antelle** [comment]
How big are your files (approximately: 100mb / 1gb / 10gb / ...)?

**Comment by ShwetaTurakhia** [comment]
the ones that are erroring out are a few 100 kbs or less than that. But one thing i have noticed is the error could be even before the file is touched.  This is the block that is throwing error. Could it have something to do with the initialization? Something makes me think that it has nothing to do with the actual file. What do you think?

zip.on("error", (err) => {
               this.logger.error("Unable to unzip the file " + zipFilePath, err);
               return reject(err);
           });

**Comment by antelle** [comment]
It shouldn't be an initialization issue, there's no additional initialization that can give this error. I would recommend reproducing it locally and adding debug info there, or adding more debug info directly on aws.  
BTW, if archives are that small, you can easily use any other library, for example, https://github.com/cthackers/adm-zip (node-stream-zip is a fork of adm-zip).
