### ISSUE TITLE
Closing Zip Stream before 'ready' causes errors

### ISSUE THREAD

**Issue by SpudNyk** [antelle/node-stream-zip#45]
When closing zip streams before all entries have been read causes an "EBADF: bad file descriptor" error as the main zip file descriptor is closed.

This is an issue when pulling entries from a large file. As you can finish your use of the zip file before the zip entries finished reading, closing it at this point should stop the reading of entries, but it does not.

I am working around it by using an error handler to swallow all errors before I close it.

**Comment by antelle** [comment]
Fixed in v1.9.0

**Comment by iambenmitchell** [comment]
If this is fixed, it is back. Just had this issue now
