### ISSUE TITLE
Is there an example of streaming unzipped file to S3?

### ISSUE THREAD

**Issue by multiaki** [antelle/node-stream-zip#46]
I am trying to stream data to s3. Here is my code:
` zip.on("ready", () => {
      zip.stream(fileName, (error, zstream) => {
        zstream.pipe(this.uploadFromStream(bucket, fileName));
.....`

When I try to upload 
`const uploadPromise = this.S3.upload({
      Bucket,
      Key,
      Body: writeStream
    }).promise();`

I am getting Error: Cannot determine length of [object Object]

**Comment by antelle** [comment]
Hi! I have no idea about S3 API, but it's the same as if it was any other node.js stream.
