### ISSUE TITLE
Error when trying to unzip MIME type application/x-zip-compressed

### ISSUE THREAD

**Issue by pip77** [antelle/node-stream-zip#50]
When trying to unzip MIME type application/x-zip-compressed, I am getting the following Error
```
{ Error: invalid distance too far back
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17) errno: -3, code: 'Z_DATA_ERROR' }
```
I have first tried with yauzl, but got `Error: unsupported compression method: 9` which, from what I read here https://github.com/thejoshwolfe/yauzl/issues/58, is meant to be deflate64. Looking for a package with deflate64 ability I tried your package, but ran into the Error above.

**Comment by antelle** [comment]
Right, we don't support deflate64 either.

**Comment by pip77** [comment]
Thank you for getting back to me. I guess you need to update your readme 
> Features: (...) deflate, deflate64, sfx, macosx/windows built-in archives

**Comment by antelle** [comment]
hm, I just tried remind why it's in the readme, and I see that here's a deflate64-archive: https://github.com/antelle/node-stream-zip/blob/master/test/ok/deflate64.zip
I wonder how it works there. Do you have an example of such archive?

**Comment by antelle** [comment]
Here's the output of zipinfo:
```
zipinfo test/ok/deflate64.zip   
Archive:  test/ok/deflate64.zip
Zip file size: 7047 bytes, number of entries: 10
-rw-a--     6.3 fat       63 bx stor 15-Feb-16 23:21 BSDmakefile
drwx---     6.3 fat        0 bx stor 15-Feb-22 12:04 doc/
drwx---     6.3 fat        0 bx stor 15-Feb-22 12:03 doc/api_assets/
-rw-a--     6.3 fat     3967 bx d64N 15-Feb-16 23:22 doc/api_assets/logo.svg
-rw-a--     6.3 fat      389 bx d64N 15-Feb-16 23:22 doc/api_assets/sh.css
-rw-a--     6.3 fat     1524 bx d64N 15-Feb-16 23:22 doc/changelog-foot.html
-rw-a--     6.3 fat     3484 bx d64N 15-Feb-16 23:22 doc/sh_javascript.min.js
drwx---     6.3 fat        0 bx stor 15-Feb-22 12:04 empty folder/
-rw-a--     6.3 fat     4457 bx d64N 15-Feb-16 23:25 README.md
-rw-a--     6.3 fat     1642 bx d64N 15-Feb-16 23:22 ??ӿ?????.html
10 files, 15526 bytes uncompressed, 5591 bytes compressed:  64.0%
```

**Comment by antelle** [comment]
I figured it out, deflate64 is not actually supported, updated the readme and published a new version, it gives a proper error.
