### ISSUE TITLE
Promise-style API needed

### ISSUE THREAD

**Issue by Frodez** [antelle/node-stream-zip#52]
Recently, I found this library for extract a zip. However, there is no api with promise-style. 
Besides, when i import the toolkit with the typescript, for example, es6-promisify, to transform the api, it not works very well, especially when it comes to the `on(event: 'ready', handler: () => void): void` or `on(event: 'entry', handler: (entry: ZipEntry) => void): void`, because the promisify toolkit can't recognize the signature of function.
It does not matter very much, but I believe that if there were api with promise-style, maybe the world will be better. 
Thank you very much.

**Comment by longieirl** [comment]
The event emitters are never triggered when the `await promise` line is added. If the promise is switched to a `.then` i.e. `promise.then(() => {console.log('Yipee')));`, it works!

Interestingly, if the ` const resources = new StreamZip({` is added after the `await promise`, it works!

```
import StreamZip from 'node-stream-zip';

export = class extends Generator {
    public constructor(args, opts) {
        super(args, opts);
    }
 
  async writing(): Promise<void> {
       
        const resources = new StreamZip({
            file: this.pluginPath(this.template, 'resources.zip'),
            storeEntries: true
        });

        if (!this.state?.project) {
            const promise = new Promise((resolve, reject) => {
                setTimeout(() => resolve('done!'), 1000);
            });
            await promise;
        }

        return new Promise((resolve, reject) => {
            // extract and copy the resources from the zip
            resources.on('error', (err) => {
                resources.close();
                reject(err);
            });
            resources.on('ready', () => {
                resources.close();
                resolve();
            });
        });
    }
};
```

**Comment by Flamenco** [comment]
99.9% of the time i just need to stream a single requested file from the zip.  Here is what i do

```js
async function getZipData(zipPath, filePath) {
  let zip;
  return new Promise((resolve, reject) => {
    zip = new StreamZip({storeEntries: true, file: zipPath});
    zip.on('ready', () => {
      const data = zip.entryDataSync(filePath)
      zip.close()
      resolve(data)
    })
    zip.on('error', e => {
      try {
        if (zip) {
          zip.close()
        }
      } catch (e) {
        // ignore
      }
      reject(e)
    })
  });
}
```

```js
const data = await getZipData('/some/path.zip', 'somefile.txt')
```

**Comment by Nenjuna** [comment]
> 99.9% of the time i just need to stream a single requested file from the zip. Here is what I do:
> 
> ```js
> async function getZipData(zipPath, filePath) {
>   let zip;
>   return new Promise((resolve, reject) => {
>     zip = new StreamZip({storeEntries: true, file: zipPath});
>     zip.on('ready', () => {
>       const data = zip.entryDataSync(filePath)
>       zip.close()
>       resolve(data)
>     })
>     zip.on('error', e => {
>       try {
>         if (zip) {
>           zip.close()
>         }
>       } catch (e) {
>         // ignore
>       }
>       reject(e)
>     })
>   });
> }
> ```
> 
> ```js
> const data = await getZipData('/some/path.zip', 'somefile.txt')
> ```
> 
> And the stream version for streaming zipped media:
> 
> ```js
> async function getZipStream(zipPath, filePath) {
>   let zip;
>   return new Promise((resolve, reject) => {
>     zip = new StreamZip({storeEntries: true, file: zipPath});
>     zip.on('ready', () => {
>       zip.stream(filePath, (err, stream) => {
>         if (err) {
>           zip.close()
>           return reject(err)
>         }
>         stream.on('end', () => {
>           zip.close()
>         })
>         resolve(stream)
>       })
>     })
>     zip.on('error', e => {
>       try {
>         if (zip) {
>           zip.close()
>         }
>       } catch (e) {
>         // ignore
>       }
>       reject(e)
>     })
>   });
> }
> ```
Wow, this really helped me. Thanks a lot

**Comment by antelle** [comment]
Finally it's here: https://github.com/antelle/node-stream-zip#async-api  
🎉
