### ISSUE TITLE
how to extract AES encrypted zip files?

### ISSUE THREAD

**Issue by hucz08** [antelle/node-stream-zip#55]
how to extract AES encrypted zip files?

module.exports.error = {};
module.exports.error['enc_aes.zip'] = function(test) {
    test.expect(1);
    var zip = new StreamZip({ file: 'test/err/enc_aes.zip' });
    zip.on('ready', function() {
        zip.stream('README.md', function(err) {
            test.equal(err, 'Entry encrypted');
            test.done();
        });
    });
};
module.exports.error['enc_zipcrypto.zip'] = function(test) {
    test.expect(1);
    var zip = new StreamZip({ file: 'test/err/enc_zipcrypto.zip' });
    zip.on('ready', function() {
        zip.stream('README.md', function(err) {
            test.equal(err, 'Entry encrypted');
            test.done();
        });
    });
};

**Comment by antelle** [comment]
Hi! I think you answered you question, the code fragment shows how to get an error.
