### ISSUE TITLE
Want a "entryDataAsync" function

### ISSUE THREAD

**Issue by Lyoko-Jeremie** [antelle/node-stream-zip#56]
i'm using this lib to read backup file in nodejs with typescript.
i have read many small BSON file (about 1~15 MB) into memory from Zip archive.

i find a `entryDataSync` function, but not find a async version.
i dont want the reading operate hang the hole process druing read disk.

can add that func ? thanks very much.

**Comment by antelle** [comment]
Hi! You should call `.stream` and then read the data from it the way you prefer.
