### ISSUE TITLE
Missing entry error emitter

### ISSUE THREAD

**Issue by alexreal1314** [antelle/node-stream-zip#57]
When you try to stream a zipEntry there is no event emitting of error coming from the entry if it fails.
Please add a ZipEntry.emit('error')

thanks

**Comment by antelle** [comment]
Hi! I came to it only now, and I see that the error is generated: https://github.com/antelle/node-stream-zip/blob/master/test/tests.js#L208

Could you please add more details: how exactly the archive is broken? Maybe we miss some errors.  
You your just find the interface of returning errors not very convenient?
