### ISSUE TITLE
Typescript error with .extract(null, ...)

### ISSUE THREAD

**Issue by beeing** [antelle/node-stream-zip#58]
Hi, I've been using this for awhile now but while trying to update some packages, this error pops out due to extract function requires entry to be a string.

So, for now, do we pass in empty string to extract all entries?

Thanks.

**Comment by antelle** [comment]
Hi! Thanks, fixed the type definition, it was because of incorrect d.ts.

**Comment by beeing** [comment]
Thanks for the quick action!
