### ISSUE TITLE
Stream-based initialization desired

### ISSUE THREAD

**Issue by jahjedtieson** [antelle/node-stream-zip#59]
A sweet addition to this project would be allowing ZipStream to be initialized either by filename or via a NodeJS.ReadableStream.  

I need to read zips present in our storage solution, but the latter hands out streams instead of filenames, because we cannot assume that the bits are accessible via a filename.

**Comment by antelle** [comment]
Hi! That's not possible unfortunately: reading zip files requires random access, for example file metadata and layout are located in the end of the file.

**Comment by jahjedtieson** [comment]
Thank you.  This makes sense.
