### ISSUE TITLE
What is  storeEntries: true    ?

### ISSUE THREAD

**Issue by PanMan** [antelle/node-stream-zip#6]
The example on the frontpage shows 
     ````storeEntries: true````    
What does this do? Thanks!

**Comment by antelle** [comment]
There are two options:
1. open archive and process each entry `zip.on('entry', function(entry) { })`
2. open archive and access any entry inside `zip.on('ready', function() { }))`, e.g. `zip.entry(name)`, `zip.entries()`, `zip.entryDataSync`, `zip.stream`.

As we can open large archives, storing entries by default could consume a lot of memory, for example if there are 1M entries inside.

I'll mention this in the readme.
