### ISSUE TITLE
Bad Archive

### ISSUE THREAD

**Issue by aparzi** [antelle/node-stream-zip#60]
I get back the bad archive error, why?

**Comment by antelle** [comment]
Do you really think I can answer the issue with this description? 🤕

**Comment by antelle** [comment]
Don't get me wrong, I'm trying to help people, but if you're blunt, I'm blunt as well. Sorry dude.

**Comment by aparzi** [comment]
Sorry @antelle. I describe my problem better.
I have this code:
`
request(options)
`
`                    .pipe(fs.createWriteStream("zipfilename.zip"))`
`                    .on('finish', async () => {`
 `                       const streamZip = new StreamZip({`
 `                           file: "zipfilename.zip.zip",`
`                            storeEntries: true,`
 `                           skipEntryNameValidation: true`
 `                       });`


But I get back the **bad archive error**

**Comment by antelle** [comment]
Ok, that's better 😌 
Now, could you please also paste the error you're getting? It should contain a stack trace that can point to the place where it happens.

**Comment by aparzi** [comment]
sorry but the stacktrace is not printed.  Can I set some debug parameters or am I wrong to print the error?

**Comment by antelle** [comment]
Let's try it offline. Take this archive somewhere and do something like this:
```js
const StreamZip = require('node-stream-zip');
const zip = new StreamZip({
    file: 'archive.zip',
    storeEntries: true
});
// extract the entry you're interested in
zip.on('error', err => { ... });
```

**Comment by aparzi** [comment]
perfect thanks, I'll keep you updated

**Comment by antelle** [comment]
If the archive is small enough to fit into memory (say, it's less than several GB), you can also try reading it with other modules, for example adm-zip, and see what happens with it.

**Comment by aparzi** [comment]
Hi @antelle , I found out that the problem is the following. I have to download a zip from an external url and store it in a temporary folder, through the fs.createWriteStream method, then the path of this temporary folder must be given to the library (**node-stream-zip**) configuration. But it seems that I try to read the temporary path first and then the writeable stream.
Do you have any idea how I can fix it?

**Comment by antelle** [comment]
I'm not sure I understand what you mean. Did it work when you saved the zip it a file?

**Comment by antelle** [comment]
Please feel free to reopen with more information. Now it's hard to tell what's going wrong.

**Comment by omardmtz** [comment]
I was facing this issue and I noticed that is not related to the module node-stream-zip. In my case, I was using a script to monitor a folder, so when a new zip file was found, the script will attempt to unzip it and run some tasks to the entries. The problem basically was that the unzip process was running even when the file was not completely "created" (it was transfered via ftp).

Same could happen in aws lambdas if there aren't conditions to wait for a completed transmission process.

That is why it "depends" on the file size, if you have some sync tasks running before the unzip process, that could be giving you some time to get the file ready.
