### ISSUE TITLE
None of the events trigger inside aws lambda

### ISSUE THREAD

**Issue by keponk** [antelle/node-stream-zip#61]
I'm attempting to download and unzip a file in aws lambda. My lambda function downloads a file from S3 and stores it in `/tmp/` which is the allowed area.

I can verify this by reading that the file exists and matches the expected filesize.

After that I have the relevant unzip code, for now just trying to list the entries. This code runs without problems in my local machine, but it silently fails in the aws lambda.  No errors are displayed, the program simply continues execution suggesting the 'error' and 'ready' events are never fired.

Any ideas on how to at least get more info of what's happening?

```
  try {
    let stats = fs.statSync(FILE_PATH);
    let fileSizeInBytes = stats["size"];
    console.log("my file fileSize: ", fileSizeInBytes);

    const zip = new StreamZip({ file: FILE_PATH });
    zip.on("error", (err) => {
      console.error("unzipping error: ", err);
    });

    zip.on("ready", () => {
      console.log("Entries: ", zip.entries());
      for (const entry of Object.values(zip.entries())) {
        const desc = entry.isDirectory ? "directory" : `${entry.size} bytes`;
        console.log(`Entry ${entry.name}: ${desc}`);
      }
      zip.close();
    });
  } catch (error) {
    console.error("error ", error);
  }
```

**Comment by antelle** [comment]
Hi! Does this code work if you run it on your laptop or somewhere else?

**Comment by keponk** [comment]
Correct. The exact same code was first run with sample data in my machine and then uploaded to AWS, where my lambda quietly executed and exits its process successfully. No errors thrown.

**Comment by antelle** [comment]
Then I can’t help here, you need to debug what’s going on there...
