### ISSUE TITLE
Read an Existing Stream

### ISSUE THREAD

**Issue by thatcort** [antelle/node-stream-zip#63]
I'd like to be able to read a zip file stream coming over the network without having to save it to disk. This doesn't seem possible with the library, but would be a very helpful addition.

**Comment by antelle** [comment]
Hi! This is unfortunately not possible. ZIP files are encoded from the end of the file, so it requires a random access device. ZIP archive cannot be read from a sequential data source without buffering.

**Comment by thatcort** [comment]
Thanks for the quick reply!
