### ISSUE TITLE
Memory usage?

### ISSUE THREAD

**Issue by PanMan** [antelle/node-stream-zip#7]
Hi!
What kind of memory usage is "normal" or "expected"? I'm using this library to extract zip files of about 400 Mb, and my node process uses >150 Mb of memory ({ rss: 152350720, heapTotal: 30214176, heapUsed: 16568248 }). That sounds like a lot, right?
Thanks!

**Comment by antelle** [comment]
Hello!
This could be normal.
What kind archive is it? Number of files, sizes?
How are you using the library, please paste a piece of code.

**Comment by PanMan** [comment]
Its a zip file of 383Mb with about 900 files in it.

The code I use is this:
````
var filesinzip=[];
var localZipfile= path.join("./","myzip.zip");

  var targetdir="/tmp/somedir";
        var zip = new StreamZip({  
            file: localZipfile,
            storeEntries: true
        });
        
        // console.log('This is zip:',zip);
        zip.on('error', function(err) { 
          cb(err)
        });
        zip.on('ready', function() {
            console.log('Entries read: ' + zip.entriesCount);
            // extract all
            zip.extract(null, targetdir, function(err, count) {
                console.log('Extracted ' + count + ' entries');   
                cb(null, filesinzip);
            });
        });
        zip.on('entry', function(entry) {
            // called on load, when entry description has been read
            // you can already stream this entry, without waiting until all entry descriptions are read (suitable for very large archives) 
            // console.log('Read entry ', entry.name);
            filesinzip.push(entry.name);
        });

````

I'm running this on heroku (as part of a larger process), and the code uses too much memory, to fit in a 512 Mb instance. The sample above uses 150Mb, but does go back to very little after garbage collection.
Any comments on the code above are welcome :)

**Comment by antelle** [comment]
Removing `storeEntries: true` might help a bit.

**Comment by PanMan** [comment]
Hmm, removing storeEntries did save a lot of memory, but it also prevented the code above from extracting any files :(
It seems ````zip.extract(null, targetdir, function(err, count) ```` does need the storeEntries to know what to extract? It doesn't say this in the readme. Separate issue?
Basically, I want to extract all files from a zip, and do a callback after that happened, with the extracted filenames. Thanks for your help!

**Comment by antelle** [comment]
Hm, yes, it will require entries to exist.
So, I don't know... If you make a memory snapshot and detect the leak, I'll happily merge it. Currently I'm ok with current memory consumption.

**Comment by antelle** [comment]
I've tried to look into it.
Here's a simple code which consumes memory as well. What's wrong with it, where's the leak?
```javascript
var stream = require('stream');
var zlib = require('zlib');

mem();
var b = new Buffer(10000000);
for (var i = 0; i < b.length; i++) {
    b[i] = Math.random();
}
for (var i = 0; i < 1000; i++) {
    console.log('#' + i, mem());
    var out = new stream.PassThrough();
    var gzip = zlib.createGzip();
    gzip.pipe(out);
    gzip.write(b);
    gzip.end();
    out = null;
}

gzip = null;
b = null;
mem();

function mem() {
    global.gc();
    return Math.round(process.memoryUsage().rss / 1024 / 1024) + 'M';
}
```

**Comment by antelle** [comment]
https://github.com/nodejs/node/issues/6139#issuecomment-207961256

**Comment by antelle** [comment]
> Note: RSS not decreasing is not an issue on its own.

**Comment by PanMan** [comment]
Thanks for looking into this! I did a lot of digging in the last few days, and even manually garbage collection doesn't reduce the RSS. I also found big differences here between OSX and Linux. But, it turns out my memory issue wasn't in the zipping part of my code. Thanks!
