### ISSUE TITLE
.close() typing is missing?

### ISSUE THREAD

**Issue by Jazcash** [antelle/node-stream-zip#72]
![image](https://user-images.githubusercontent.com/1434248/107864611-ccab8380-6e55-11eb-9572-0e12dcd8cb02.png)

Currently having to cast as `any` to call `.close()`.

**Comment by Jazcash** [comment]
Sorry I'm dumb, I guess async api closes automatically

**Comment by antelle** [comment]
No it doesn’t! I’ll check why it’s missing today

**Comment by antelle** [comment]
Done, added it in `1.13.1`.
