### ISSUE TITLE
mkdir recursive?

### ISSUE THREAD

**Issue by GumbyMan82** [antelle/node-stream-zip#77]
I'm having troubles extracting an archive that causes node-stream-zip to create folders in bottom-up order.
So instead of creating

```
Folder1
  Subfolder1
    Subsubfolder1
```

node-stream-zip tries fo create `Folder1/Subfolder1/Subsubfolder1` first, which causes the fs.mkdir function to throw an ENOENT error since the parent directories (Folder1/Subfolder1) do not exists. I'm not sure what defines the order of folders being created, maybe its something within the zip.

It would help to call mkdir with recursive option (function `createDirectories` ), but i'm unsure it that causes any other sideffects hence the issue to discuss it

```
        fs.mkdir(dir, {recursive: true} ,(err) => {
            if (err && err.code !== 'EEXIST') {
                return callback(err);
            }
            createDirectories(baseDir, dirs, callback);
        });
```

BTW, i'm using  the async apit to extract a whole ZIP, like int the example
fs.mkdirSync('extracted');
```
const count = await zip.extract(null, './extracted');
console.log(`Extracted ${count} entries`);
await zip.close();
```

**Comment by antelle** [comment]
Hi It should be fine to add it of course

**Comment by DiscoNova** [comment]
I don't see any problems with using the recursive-flag ... after all, that is what it is for :)

**Comment by antelle** [comment]
Yes, I think it was not added before because it was not supported in node.js

**Comment by DiscoNova** [comment]
Curious ... I have felt like it has "always" been there, but you're correct - it was only added in v10.12.0 ... TIL :)

**Comment by antelle** [comment]
I remember I was thinking "how do I create directories recursively without dependencies?" and implemented [this](https://github.com/antelle/node-stream-zip/blob/master/node_stream_zip.js#L605-L607), which worked in simple cases but not for deeply nested archives. Glad that it can be easily fixed now!
