### ISSUE TITLE
Support AES encrypted files

### ISSUE THREAD

**Issue by jobe451** [antelle/node-stream-zip#79]
Feature request: Support AES encrypted files

That state on this is a bit ambiguous. On the readme this is described as a "known issue". In #55 I read a somewhat grumpy response.

Would be fair to declare this either as a planned feature or to describe that this is neither supported nor that there is a plan to ever support it.

**Comment by antelle** [comment]
Hi! At the moment it's out of scope of this library, clarified it in the readme: https://github.com/antelle/node-stream-zip/commit/fa2d07a665f18170a7eac6c28c5c0beb66295c9e
