### ISSUE TITLE
Feature request: read ZIP file from input stream

### ISSUE THREAD

**Issue by jghaines** [antelle/node-stream-zip#8]
It looks like the current interface requires a Filename. 

I would be great if I could pass in a stream as the ZIP source

**Comment by jghaines** [comment]
Although, according to this: https://github.com/thejoshwolfe/yauzl#no-streaming-unzip-api
Streaming a ZIP is fraught with peril...

**Comment by antelle** [comment]
Yes, zip files are read from the end: it's impossible to read zip files as a stream.
