### ISSUE TITLE
StreamZipAsync type is not exported

### ISSUE THREAD

**Issue by ferdingler** [antelle/node-stream-zip#80]
Hi, I'm having the following situation where I would like to declare the variable zip as a `StreamZipAsync` type before intializing it, but I can't because that type is not exported. 

```js
import NodeStreamZip from 'node-stream-zip';

let zip: StreamZipAsync; // <--- I can't use StreamZipAsync because it is not exported

try {
    zip = new NodeStreamZip.async({
        file: `myfile.zip`,
        storeEntries: true
    });
} catch (err) {
    console.error('Failed to open zip', err);
}

const entries = Object.values(await zip.entries());

// code continues ...
```

Can you please advise on how to make use of that type? Thanks in advance

**Comment by antelle** [comment]
just remove the try-catch, the constructor will never throw

**Comment by antelle** [comment]
ok, done
