### ISSUE TITLE
How can I unzip a stream?

### ISSUE THREAD

**Issue by justinmchase** [antelle/node-stream-zip#81]
I see `new ZipStream.async({ file })` can load a _file_ to be unzipped but how would I do:

```ts
const stream = download(url) // Readable
const zip = new ZipStream.async({ stream })
```

**Comment by antelle** [comment]
Hi! You cannot, because zip files are read from their end, so you need to have a random access stream, not a sequential one.

**Comment by justinmchase** [comment]
Ok, well this one works 🤷 
https://www.npmjs.com/package/unzip-stream

Though your api is nicer so I thought I'd ask.
