### ISSUE TITLE
Maybe you can add an encoding parameter

### ISSUE THREAD

**Issue by timi137137** [antelle/node-stream-zip#84]
In some cases where you need to specify the encoding to extract the file so that the file name will output correctly, maybe you can add one?

there an immature package: https://www.npmjs.com/package/node-stream-zip-iconv

**Comment by antelle** [comment]
That's a good idea actually, and we don't need iconv because node.js has a built-in text encoder/decoder.

**Comment by timi137137** [comment]
Oh, this is good news for me, because I wrote a library by myself while waiting for the reply. With apologies, I hope to use this new feature soon

Possible problems:
Garbled characters may occur when no encoding is specified
The folder contains unrecognized characters in Windows, for example,? *- Causes decompression failure

**Comment by antelle** [comment]
Done, added `nameEncoding` in 61eb83e29d9e127935b04553cc9543e6bc86d3cd
Please note that it works starting from Node.js v12, but it doesn't support a lot of encoding. Proper encoding support is implemented in Node.js v14.
