### ISSUE TITLE
unable to extract full data of >1MB .docx files

### ISSUE THREAD

**Issue by suneel-eng** [antelle/node-stream-zip#86]
I am trying to extract >1MB .docx files, but I am not getting full data of document.xml and styles.xml files. and I am not getting any error also. Is there any configuration needs to be done or any other way to do this. please let me know...

Thanks in advance.

**Comment by antelle** [comment]
Hi! No, there's no extra configuration needed, it should work. If there's no error, it's most likely an issue with code.

**Comment by suneel-eng** [comment]
@antelle , thanks for the reply.

I did mistake in my code. now it's working fine.
