### ISSUE TITLE
Error when trying to pass Zipped buffer to StreamZip

### ISSUE THREAD

**Issue by tagoad** [antelle/node-stream-zip#87]
So I haven't used your package before but I need to unzip a csv file that is being returned via fetch, and yours was top of the list. I am running into was seems like contradicting errors when i try to pass the buffer. I had originally passed a stream and got the following error:
The "path" argument must be of type string or an instance of Buffer or URL. Received an instance of Readable
When I changed it to pass the buffer from the request i then got this error:
The argument 'path' must be a string or Uint8Array without null bytes. Received <Buffer ....
 Here is the code
```
let buffer = await httpRes.buffer()
let fileStream = bufferToStream(buffer)
let stream = new StreamZip({
          file: fileStream,
          storeEntries: true
 })
```
Any guidance would be greatly appreciated.

**Comment by antelle** [comment]
Hi! You can't pass this kind of stream to the library, it works with files only and expects path as argument.

**Comment by tagoad** [comment]
> Hi! You can't pass this kind of stream to the library, it works with files only and expects path as argument.

Shoot, i guess i misunderstood the article i was reading then. Thanks for the quick reply! Would you happen to know a package that could do this?

**Comment by antelle** [comment]
Perhaps `adm-zip`? No idea to be honest.
