### ISSUE TITLE
[Question] How to check if the file is corrupted?

### ISSUE THREAD

**Issue by felinto-dev** [antelle/node-stream-zip#88]
I would check ONLY if the file is corrupted. I would use the less memory and CPU possible.

What method should I use?

**Comment by antelle** [comment]
Hi,
You just read the file without extracting any entry. Then it should throw an exception if it's invalid.

**Comment by felinto-dev** [comment]
In the examples shown in the documentation, I necessarily need to know a valid example file. Users can upload any ZIP file they want and I won't know the contents. I just want to know if the file is corrupted. What do you suggest?
