### ISSUE TITLE
Stream zip is skipping root folder

### ISSUE THREAD

**Issue by themese** [antelle/node-stream-zip#89]
Hi,
I'm new to the plugin, I just have an issue I can't seem to get my head around it.

I have a file structure such as this:

- testFolder.zip
    - testFolder
        - newFolder
            - file 1
            - file 2

I'm building a runtime object T and looping through the files and folders, pushing them into an array called items of type object T. 

My problem is that the first item that gets logged out is `testFolder/newFolder` while I expect it to be `testFolder`. I'm confused because the paths themselves are correct, which means that the path for `newFolder` is `testFolder/newFolder` as well as for the rest of files, but because I don't get that first `testFolder` I don't get it to be pushed to my array. 
I understand I could do it manually, but this is not something that I would like, as the moment I have a different tree structure it would fail 
What am I doing wrong? I've tried using the on entry function but I got the same results.

```
await Promise.all(Object.values(entries).map(async entry => {

    console.log('entry: ', entry.path); // <--- this log

    const splittedPath = entry.name.split('/').filter((slices) => slices !== '');
    const nodeName = splittedPath[splittedPath.length - 1];
    if (entry.isDirectory) {
      items.push({
        type: 'Directory',
        name: nodeName,
        path: entry.name,
        children: [],
      });
    } else {
      items.push({
        content: await zip.entryData(entry.name),
        name: nodeName,
        path: entry.name,
        type: 'File',
        size: entry.size,
      });
    }
  }));
```

Note: This is async as the property content when the item is a file needs to be a Buffer, so I await it.

Thanks in advance!

**Comment by antelle** [comment]
Hi! The library just returns folders from the zip archive as they occur. Sometimes they're present, sometimes absent. So, in this case you should be prepared that a folder might be absent...

**Comment by themese** [comment]
@antelle thanks for the response!
 
I don't quite follow you. You're saying that "The library just returns folders from the zip archive as they occur" which makes sense and it's what I expect, and there lies my issue. That the first entry that the zip registers is `newFolder` with path/name `testFolder/newFolder` while I expected `testFolder` to be the first and then `testFolder/newFolder`

**Comment by antelle** [comment]
Well, that's how it's encoded inside the zip archive, I suppose.
